server:
  port: 9091

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/ykb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 1000ms
#    password: 123456

  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: LEGACYHTML5

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seecen.dd.xxxsys.dao.domain
logging:
  level:
    com.seecen: debug

devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署

#pagehelper:
#  helper-dialect: mysql
#  #分页合理化 （超过最后一页或者第一页的处理）
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#?serverTimezone=GMT>>>>>>> .r2367
